name: Тестирование и развертывания проекта

on: 
  push:
    branches: [cicd]

jobs:
  tests:
    runs-on: ubuntu20.04
    env:
      SECRET_KEY: ${DB_USER.SECRET_KEY}
      DB_NAME: 'crud'
      DB_USER: 'ivan'
      DB_PASSWORD: 1234

    services:
      postgres_main:
        image: postgres:12
        env:
          POSTGRES_DB: ${env.DB_NAME}
          POSTGRES_USER: ${env.DB_USER}
          POSTGRES_PASSWORD: ${env.DB_PASSWORD}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Проверка репозитория
        uses: actions/checkout@v2
      - name: Установка python и настройка окружения
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      
      - name: Надпись
        run: echo 'eeee'
